/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type Generated<T> = ColumnType<T, undefined, undefined>;

export interface Users {
  avatar_initials: string | null;
  created_at: Generated<Date>;
  email: string;
  id: Generated<string>;
  name: string;
  password_hash: string;
  updated_at: Generated<Date>;
}

export type UserSelect = Selectable<Users>;
export type UserNew = Insertable<Users>;
export type UserUpdate = Updateable<Users>;

export interface DB {
  Users: Users;
}
