/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType, GeneratedAlways } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Users {
  id: Generated<string>;
  avatar_initials: string;
  created_at: Generated<Timestamp>;
  email: string;
  name: string;
  password_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  Users: Users;
}
